version: '3'
services:
    app:
        # 起動イメージ
        image: node:16
        env_file:
            - .env
        # 環境変数
        environment:
            - DEBUG=app:*
        tty: true
        # ホスト側のポート：コンテナのポート
        ports:
            - '8080:8080'
        # ホスト側のsrcをコンテナのappにマウント
        volumes:
            - ./src:/app
            - ./node_modules:/app/node_modules
            - ./package.json:/app/package.json
        # 起動時のカレントフォルダ
        working_dir: /app
        # 起動後に実行するコマンド
        command: sh -c 'npm install; npx tsc; npm run dev'